// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ReduktuMi.Views {
    
    
    public partial class MainWindow {
        
        private Gtk.Fixed fixed3;
        
        private Gtk.VBox vbox1;
        
        private Gtk.HButtonBox hbuttonbox1;
        
        private Gtk.Button btnAdd;
        
        private Gtk.Button btnRemove;
        
        private Gtk.TreeView treeViewImages;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget ReduktuMi.Views.MainWindow
            this.Name = "ReduktuMi.Views.MainWindow";
            this.Title = Mono.Unix.Catalog.GetString("MainWindow");
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            // Container child ReduktuMi.Views.MainWindow.Gtk.Container+ContainerChild
            this.fixed3 = new Gtk.Fixed();
            this.fixed3.Name = "fixed3";
            this.fixed3.HasWindow = false;
            // Container child fixed3.Gtk.Fixed+FixedChild
            this.vbox1 = new Gtk.VBox();
            this.vbox1.WidthRequest = 301;
            this.vbox1.HeightRequest = 392;
            this.vbox1.Name = "vbox1";
            this.vbox1.Spacing = 6;
            // Container child vbox1.Gtk.Box+BoxChild
            this.hbuttonbox1 = new Gtk.HButtonBox();
            this.hbuttonbox1.Name = "hbuttonbox1";
            this.hbuttonbox1.LayoutStyle = ((Gtk.ButtonBoxStyle)(2));
            // Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
            this.btnAdd = new Gtk.Button();
            this.btnAdd.CanFocus = true;
            this.btnAdd.Name = "btnAdd";
            this.btnAdd.UseUnderline = true;
            // Container child btnAdd.Gtk.Container+ContainerChild
            Gtk.Alignment w1 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w2 = new Gtk.HBox();
            w2.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w3 = new Gtk.Image();
            w3.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-add", Gtk.IconSize.Button, 20);
            w2.Add(w3);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w5 = new Gtk.Label();
            w5.LabelProp = Mono.Unix.Catalog.GetString("Add");
            w5.UseUnderline = true;
            w2.Add(w5);
            w1.Add(w2);
            this.btnAdd.Add(w1);
            this.hbuttonbox1.Add(this.btnAdd);
            Gtk.ButtonBox.ButtonBoxChild w9 = ((Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1[this.btnAdd]));
            w9.Expand = false;
            w9.Fill = false;
            // Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
            this.btnRemove = new Gtk.Button();
            this.btnRemove.CanFocus = true;
            this.btnRemove.Name = "btnRemove";
            this.btnRemove.UseUnderline = true;
            // Container child btnRemove.Gtk.Container+ContainerChild
            Gtk.Alignment w10 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w11 = new Gtk.HBox();
            w11.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w12 = new Gtk.Image();
            w12.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-remove", Gtk.IconSize.Button, 20);
            w11.Add(w12);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w14 = new Gtk.Label();
            w14.LabelProp = Mono.Unix.Catalog.GetString("Remove");
            w14.UseUnderline = true;
            w11.Add(w14);
            w10.Add(w11);
            this.btnRemove.Add(w10);
            this.hbuttonbox1.Add(this.btnRemove);
            Gtk.ButtonBox.ButtonBoxChild w18 = ((Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1[this.btnRemove]));
            w18.Position = 1;
            w18.Expand = false;
            w18.Fill = false;
            this.vbox1.Add(this.hbuttonbox1);
            Gtk.Box.BoxChild w19 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbuttonbox1]));
            w19.Position = 0;
            w19.Expand = false;
            w19.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.treeViewImages = new Gtk.TreeView();
            this.treeViewImages.HeightRequest = 314;
            this.treeViewImages.CanFocus = true;
            this.treeViewImages.Name = "treeViewImages";
            this.treeViewImages.Reorderable = true;
            this.treeViewImages.SearchColumn = 1;
            this.vbox1.Add(this.treeViewImages);
            Gtk.Box.BoxChild w20 = ((Gtk.Box.BoxChild)(this.vbox1[this.treeViewImages]));
            w20.Position = 1;
            this.fixed3.Add(this.vbox1);
            Gtk.Fixed.FixedChild w21 = ((Gtk.Fixed.FixedChild)(this.fixed3[this.vbox1]));
            w21.X = 15;
            w21.Y = 17;
            this.Add(this.fixed3);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 604;
            this.DefaultHeight = 437;
            this.Show();
            this.btnAdd.Clicked += new System.EventHandler(this.OnBtnAddClicked);
            this.btnRemove.Clicked += new System.EventHandler(this.OnBtnRemoveClicked);
        }
    }
}
